### ISSUE TITLE
env.get_dataset Can't read data (inflate() failed)

### ISSUE THREAD

**Issue by nuomizai** [Farama-Foundation/D4RL#160]
I tried to downlowd the door-expert-v1 datasets from [link](http://rail.eecs.berkeley.edu/datasets/offline_rl/hand_dapg_v1/door-expert-v1.hdf5) to `../d4rl_mode/datasets/door-expert-v1.hdf5`, and load datasets using the following command

```
env = gym.make('door-expert-v1')
env.get_dataset('../d4rl_model/datasets/door-expert-v1.hdf5')
```

However, I got the Error as 

```
(mjrl-env) quan@quan-System-Product-Name:~/parrot$ ./test.sh
Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
/home/quan/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/glfw/__init__.py:906: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
pybullet build time: Dec  1 2021 18:33:04
/home/quan/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
load datafile:  10%|██████████████▌                                                                                                                                          | 2/21 [00:01<00:09,  1.92it/s]
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    dataset = env.get_dataset('../d4rl_model/datasets/door-expert-v1.hdf5')
  File "/home/quan/d4rl/d4rl/offline_env.py", line 80, in get_dataset
    data_dict[k] = dataset_file[k][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/quan/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 710, in __getitem__
    return self._fast_reader.read(args)
  File "h5py/_selector.pyx", line 366, in h5py._selector.Reader.read
OSError: Can't read data (inflate() failed)
```

Does anyone know what's wrong with the datasets?

**Comment by CeyaoZhang** [comment]
I have the same problem orz
```
>>> import d4rl 
Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
/root/miniconda3/envs/mujoco200+/lib/python3.7/site-packages/glfw/__init__.py:906: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
pybullet build time: May 20 2022 19:43:01
```

**Comment by nuomizai** [comment]
> I have the same problem orz

I have solved my problem by running the command again. It seemed that there is nothing wrong with your running. Just ignore the warnings and everything works fine.
